import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { db } from '../../firebase/firebase';
import { Item } from '../components/item';
import styles from '../styles/Home.module.css';

type ItemType = {
  name: string;
  price: number;
  imageId: string;
};

type ListType = {
  items: ItemType[];
};

const List: NextPage = ({ items }: ListType) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        {items.map((item: ItemType, index: number) => (
          <Item key={index} name={item.name} price={item.price} imageId={item.imageId} />
        ))}
      </main>
    </div>
  );
};

export default List;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const colRef = db.collection('items');
  const cardSnap = await colRef.get();
  const items = cardSnap.docs.map((doc) => ({
    id: doc.id,
    ...doc.data(),
  }));
  return { props: { items } };
};
